name: VSCode Extension CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-24.04

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run vscode:prepackage
    - run: npm run vscode:package

    - run: npm run vscode:publish -p "${{ secrets.AZURE_ACCESS_TOKEN }}"
      if: github.event_name == 'release' && github.event.action == 'created'

    - uses: actions/upload-artifact@v4
      with:
        path: "*.vsix"
        if-no-files-found: error

